services:
  postgres:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_DB: logs_db
      POSTGRES_USER: logs_user
      POSTGRES_PASSWORD: logs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U logs_user -d logs_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    restart: always
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: log_analytics_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_HEAP_OPTS: "-Xmx128m -Xms64m"
    ports:
      - "2181:2181"
    mem_limit: 192m

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: log_analytics_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_HEAP_OPTS: "-Xmx256m -Xms128m"
    ports:
      - "9092:9092"
    mem_limit: 320m

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: log_analytics_clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    environment:
      CLICKHOUSE_DB: logs_db
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-config.xml:/etc/clickhouse-server/config.d/memory.xml
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8123/ping"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 60s

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://logs_user:logs_password@postgres:5432/logs_db
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_DB: logs_db
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_started
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://logs_user:logs_password@postgres:5432/logs_db
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_DB: logs_db
      REDIS_URL: redis://redis:6379/0
    command: python -m src.workers.consumer
    volumes:
      - .:/app

  stream-processor:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_started
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://logs_user:logs_password@postgres:5432/logs_db
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_DB: logs_db
      REDIS_URL: redis://redis:6379/0
    command: python -m src.workers.stream_processor
    volumes:
      - .:/app

  alert-processor:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      kafka:
        condition: service_started
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://logs_user:logs_password@postgres:5432/logs_db
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_DB: logs_db
    command: python -m src.workers.alert_processor
    volumes:
      - .:/app

  archiver:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://logs_user:logs_password@postgres:5432/logs_db
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: 9000
      CLICKHOUSE_DB: logs_db
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION:-us-east-2}
      S3_BUCKET: ${S3_BUCKET:-log-analytics-archive-tejas}
      ARCHIVE_INTERVAL_SECONDS: 300
    command: python -m src.workers.archiver
    volumes:
      - .:/app

volumes:
  postgres_data:
  redis_data:
  clickhouse_data:
